#macro HUD_DEBUG true

// STYLE MACROS
#macro HUD_STYLE_CLASSIC 1
#macro HUD_STYLE_BLOCK 2

// SPRITE IMG INDEX MACROS
// icon
#macro HUD_ICON_KIN 0
#macro HUD_ICON_LIVES 1
#macro HUD_ICON_FIRE1_HINT 2
#macro HUD_ICON_FIRE3_HINT 3

// dashbar
#macro HUD_DASHBAR_OUTLINE 0
#macro HUD_DASHBAR_FILL 1
#macro HUD_DASHBAR_ICON 2

// chargebar
#macro HUD_CHARGEBAR_OUTLINE 0
#macro HUD_CHARGEBAR_FILL 1
// chargebar icons
#macro HUD_CHARGEBAR_ICON_FIRE2 0

// SPRITE IMG INDEX CONTROLS
#macro HUD_CONTROL_A  0
#macro HUD_CONTROL_B  1
#macro HUD_CONTROL_X  2
#macro HUD_CONTROL_Y  3
#macro HUD_CONTROL_RB 4
#macro HUD_CONTROL_LB 5
#macro HUD_CONTROL_LT 6
#macro HUD_CONTROL_RT 7
#macro HUD_CURSOR_AIM 0
#macro HUD_CURSOR_POINTER 1
