// STYLE MACROS
#macro HUD_STYLE_CLASSIC 1
#macro HUD_STYLE_BLOCK 2

#macro HUD_STYLE HUD_STYLE_BLOCK

// SPRITE IMG INDEX MACROS
// icon
#macro HUD_ICON_KIN 0
#macro HUD_ICON_LIVES 1

// dashbar
#macro HUD_DASHBAR_OUTLINE 0
#macro HUD_DASHBAR_FILL 1
